"""add file_imports table

Revision ID: 9ff893b2b12d
Revises: 985e6970236d
Create Date: 2026-05-06 21:53:53.226415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff893b2b12d'
down_revision: Union[str, Sequence[str], None] = '985e6970236d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_imports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.Text(), nullable=False),
    sa.Column('source_file', sa.Text(), nullable=False),
    sa.Column('imported_file', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.repo_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file_imports')
    # ### end Alembic commands ###
