"""add_error_message_to_repos

Revision ID: cf4fa4eefc20
Revises: 92ac5b8fd6cf
Create Date: 2026-06-24 13:08:10.285272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf4fa4eefc20'
down_revision: Union[str, Sequence[str], None] = '92ac5b8fd6cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repos', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repos', 'error_message')
    # ### end Alembic commands ###
